### ISSUE TITLE
Broken hashCode method in `Requirement` class breaks Hibernate

### ISSUE THREAD

**Issue by TPolzer** [uv48uson/amos-ss15-proj3#157]
After starting our application I just got the following backtrace:
```
INFO: HHH000232: Schema update complete
java.lang.NullPointerException
        at de.fau.osr.core.db.domain.Requirement.hashCode(Requirement.java:111)
        at java.util.HashMap.hash(HashMap.java:338)
        at java.util.HashMap.put(HashMap.java:611)
        at java.util.HashSet.add(HashSet.java:219)
        at java.util.AbstractCollection.addAll(AbstractCollection.java:344)
        at org.hibernate.collection.internal.PersistentSet.endRead(PersistentSet.java:344)
        at org.hibernate.engine.loading.internal.CollectionLoadContext.endLoadingCollection(CollectionLoadContext.java:251)
        at org.hibernate.engine.loading.internal.CollectionLoadContext.endLoadingCollections(CollectionLoadContext.java:238)
        at org.hibernate.engine.loading.internal.CollectionLoadContext.endLoadingCollections(CollectionLoadContext.java:211)
        at org.hibernate.loader.plan.exec.process.internal.CollectionReferenceInitializerImpl.endLoading(CollectionReferenceInitializerImpl.java:168)
        at org.hibernate.loader.plan.exec.process.internal.AbstractRowReader.finishLoadingCollections(AbstractRowReader.java:255)
        at org.hibernate.loader.plan.exec.process.internal.AbstractRowReader.finishUp(AbstractRowReader.java:218)
        at org.hibernate.loader.plan.exec.process.internal.ResultSetProcessorImpl.extractResults(ResultSetProcessorImpl.java:140)
        at org.hibernate.loader.plan.exec.internal.AbstractLoadPlanBasedLoader.executeLoad(AbstractLoadPlanBasedLoader.java:138)
        at org.hibernate.loader.plan.exec.internal.AbstractLoadPlanBasedLoader.executeLoad(AbstractLoadPlanBasedLoader.java:102)
        at org.hibernate.loader.collection.plan.AbstractLoadPlanBasedCollectionInitializer.initialize(AbstractLoadPlanBasedCollectionInitializer.java:100)
        at org.hibernate.persister.collection.AbstractCollectionPersister.initialize(AbstractCollectionPersister.java:693)
        at org.hibernate.event.internal.DefaultInitializeCollectionEventListener.onInitializeCollection(DefaultInitializeCollectionEventListener.java:92)
        at org.hibernate.internal.SessionImpl.initializeCollection(SessionImpl.java:1933)
        at org.hibernate.collection.internal.AbstractPersistentCollection.forceInitialization(AbstractPersistentCollection.java:683)
        at org.hibernate.engine.internal.StatefulPersistenceContext.initializeNonLazyCollections(StatefulPersistenceContext.java:894)
        at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:360)
        at org.hibernate.loader.Loader.doList(Loader.java:2554)
        at org.hibernate.loader.Loader.doList(Loader.java:2540)
        at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2370)
        at org.hibernate.loader.Loader.list(Loader.java:2365)
        at org.hibernate.loader.criteria.CriteriaLoader.list(CriteriaLoader.java:126)
        at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1718)
        at org.hibernate.internal.CriteriaImpl.list(CriteriaImpl.java:380)
        at de.fau.osr.core.db.dao.impl.AbstractDefaultDao.getAllObjects(AbstractDefaultDao.java:128)
        at de.fau.osr.core.db.dao.impl.RequirementDaoImplementation.getAllRequirements(RequirementDaoImplementation.java:66)
        at de.fau.osr.core.db.DBDataSource.doGetAllRequirements(DBDataSource.java:143)
        at de.fau.osr.core.db.DataSource.getAllRequirements(DataSource.java:167)
        at de.fau.osr.core.db.CompositeDataSource.doGetAllRequirements(CompositeDataSource.java:85)
        at de.fau.osr.core.db.DataSource.getAllRequirements(DataSource.java:167)
        at de.fau.osr.bl.Tracker.getRequirements(Tracker.java:165)
        at de.fau.osr.gui.Model.TrackerAdapter.getAllRequirements(TrackerAdapter.java:96)
        at de.fau.osr.gui.Model.Collection_Model_Impl.getRequirements(Collection_Model_Impl.java:56)
        at de.fau.osr.gui.Controller.GuiController.lambda$requirementsFromDB$15(GuiController.java:190)
        at de.fau.osr.gui.Controller.GuiController$$Lambda$17/1865239.get(Unknown Source)
        at de.fau.osr.gui.Controller.Transformer.process(Transformer.java:64)
        at de.fau.osr.gui.Controller.GuiController.requirementsFromDB(GuiController.java:205)
        at de.fau.osr.gui.Controller.GuiController.configureApplication(GuiController.java:1007)
        at de.fau.osr.gui.View.ElementHandler.Configuration_ElementHandler$SwingAction.actionPerformed(Configuration_ElementHandler.java:258)
        at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
        at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2346)
        at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
        at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
        at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
        at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
        at java.awt.Component.processMouseEvent(Component.java:6525)
        at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
        at java.awt.Component.processEvent(Component.java:6290)
        at java.awt.Container.processEvent(Container.java:2234)
        at java.awt.Component.dispatchEventImpl(Component.java:4881)
        at java.awt.Container.dispatchEventImpl(Container.java:2292)
        at java.awt.Component.dispatchEvent(Component.java:4703)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
        at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
        at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
        at java.awt.Container.dispatchEventImpl(Container.java:2278)
        at java.awt.Window.dispatchEventImpl(Window.java:2750)
        at java.awt.Component.dispatchEvent(Component.java:4703)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.awt.EventQueue$4.run(EventQueue.java:731)
        at java.awt.EventQueue$4.run(EventQueue.java:729)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Jul 13, 2015 6:02:00 PM org.hibernate.engine.loading.internal.LoadContexts cleanup
WARN: HHH000100: Fail-safe cleanup (collections) : org.hibernate.engine.loading.internal.CollectionLoadContext@6539dce<rs=org.postgresql.jdbc4.Jdbc4ResultSet@3e080386>
java.lang.NullPointerException
        at de.fau.osr.core.db.domain.Requirement.hashCode(Requirement.java:111)
        at java.util.HashMap.hash(HashMap.java:338)
        at java.util.HashMap.put(HashMap.java:611)
        at java.util.HashSet.add(HashSet.java:219)
        at java.util.AbstractCollection.addAll(AbstractCollection.java:344)
        at org.hibernate.collection.internal.PersistentSet.endRead(PersistentSet.java:344)
        at org.hibernate.engine.loading.internal.CollectionLoadContext.endLoadingCollection(CollectionLoadContext.java:251)
        at org.hibernate.engine.loading.internal.CollectionLoadContext.endLoadingCollections(CollectionLoadContext.java:238)
        at org.hibernate.engine.loading.internal.CollectionLoadContext.endLoadingCollections(CollectionLoadContext.java:211)
        at org.hibernate.loader.plan.exec.process.internal.CollectionReferenceInitializerImpl.endLoading(CollectionReferenceInitializerImpl.java:168)
        at org.hibernate.loader.plan.exec.process.internal.AbstractRowReader.finishLoadingCollections(AbstractRowReader.java:255)
        at org.hibernate.loader.plan.exec.process.internal.AbstractRowReader.finishUp(AbstractRowReader.java:218)
        at org.hibernate.loader.plan.exec.process.internal.ResultSetProcessorImpl.extractResults(ResultSetProcessorImpl.java:140)
        at org.hibernate.loader.plan.exec.internal.AbstractLoadPlanBasedLoader.executeLoad(AbstractLoadPlanBasedLoader.java:138)
        at org.hibernate.loader.plan.exec.internal.AbstractLoadPlanBasedLoader.executeLoad(AbstractLoadPlanBasedLoader.java:102)
        at org.hibernate.loader.collection.plan.AbstractLoadPlanBasedCollectionInitializer.initialize(AbstractLoadPlanBasedCollectionInitializer.java:100)
        at org.hibernate.persister.collection.AbstractCollectionPersister.initialize(AbstractCollectionPersister.java:693)
        at org.hibernate.event.internal.DefaultInitializeCollectionEventListener.onInitializeCollection(DefaultInitializeCollectionEventListener.java:92)
        at org.hibernate.internal.SessionImpl.initializeCollection(SessionImpl.java:1933)
        at org.hibernate.collection.internal.AbstractPersistentCollection.forceInitialization(AbstractPersistentCollection.java:683)
        at org.hibernate.engine.internal.StatefulPersistenceContext.initializeNonLazyCollections(StatefulPersistenceContext.java:894)
        at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:360)
        at org.hibernate.loader.Loader.doList(Loader.java:2554)
        at org.hibernate.loader.Loader.doList(Loader.java:2540)
        at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2370)
        at org.hibernate.loader.Loader.list(Loader.java:2365)
        at org.hibernate.loader.criteria.CriteriaLoader.list(CriteriaLoader.java:126)
        at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1718)
        at org.hibernate.internal.CriteriaImpl.list(CriteriaImpl.java:380)
        at de.fau.osr.core.db.dao.impl.AbstractDefaultDao.getAllObjects(AbstractDefaultDao.java:128)
        at de.fau.osr.core.db.dao.impl.RequirementDaoImplementation.getAllRequirements(RequirementDaoImplementation.java:66)
        at de.fau.osr.core.db.DBDataSource.doGetAllReqCommitRelations(DBDataSource.java:61)
        at de.fau.osr.core.db.DataSource.getAllReqCommitRelations(DataSource.java:154)
        at de.fau.osr.core.db.CompositeDataSource.doGetAllReqCommitRelations(CompositeDataSource.java:95)
        at de.fau.osr.core.db.DataSource.getAllReqCommitRelations(DataSource.java:154)
        at de.fau.osr.bl.Tracker.getAllReqCommitRelations(Tracker.java:283)
        at de.fau.osr.bl.Tracker.getAllCommitReqRelations(Tracker.java:293)
        at de.fau.osr.bl.Tracker.getCommitsByIds(Tracker.java:583)
        at de.fau.osr.bl.Tracker.getCommits(Tracker.java:157)
        at de.fau.osr.gui.Model.TrackerAdapter.getAllCommits(TrackerAdapter.java:244)
        at de.fau.osr.gui.Model.Collection_Model_Impl.getCommitsFromDB(Collection_Model_Impl.java:150)
        at de.fau.osr.gui.Controller.GuiController.lambda$commitsFromDBForManagementTab$22(GuiController.java:279)
        at de.fau.osr.gui.Controller.GuiController$$Lambda$25/463866564.get(Unknown Source)
        at de.fau.osr.gui.Controller.Transformer.process(Transformer.java:64)
        at de.fau.osr.gui.Controller.GuiController.commitsFromDBForManagementTab(GuiController.java:290)
        at de.fau.osr.gui.Controller.GuiController.initLinkageManagementTab(GuiController.java:298)
        at de.fau.osr.gui.Controller.GuiController.configureApplication(GuiController.java:1009)
        at de.fau.osr.gui.View.ElementHandler.Configuration_ElementHandler$SwingAction.actionPerformed(Configuration_ElementHandler.java:258)
        at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
        at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2346)
        at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
        at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
        at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
        at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
        at java.awt.Component.processMouseEvent(Component.java:6525)
        at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
        at java.awt.Component.processEvent(Component.java:6290)
        at java.awt.Container.processEvent(Container.java:2234)
        at java.awt.Component.dispatchEventImpl(Component.java:4881)
        at java.awt.Container.dispatchEventImpl(Container.java:2292)
        at java.awt.Component.dispatchEvent(Component.java:4703)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
        at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
        at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
        at java.awt.Container.dispatchEventImpl(Container.java:2278)
        at java.awt.Window.dispatchEventImpl(Window.java:2750)
        at java.awt.Component.dispatchEvent(Component.java:4703)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.awt.EventQueue$4.run(EventQueue.java:731)
        at java.awt.EventQueue$4.run(EventQueue.java:729)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Jul 13, 2015 6:02:00 PM org.hibernate.engine.loading.internal.LoadContexts cleanup
WARN: HHH000100: Fail-safe cleanup (collections) : org.hibernate.engine.loading.internal.CollectionLoadContext@129dc852<rs=org.postgresql.jdbc4.Jdbc4ResultSet@a2fa730>
```
And no information was fetched from database anymore.

**Comment by TPolzer** [comment]
The cause for this were automatically inserted requirements with NULL storypoints.
