### ISSUE TITLE
GUI produces java.lang.ArrayStoreException

### ISSUE THREAD

**Issue by TPolzer** [uv48uson/amos-ss15-proj3#25]
~~While running the GUI today I got several NullPointerExceptions in the console.~~ (I don't know what I saw there...)
```
Exception in thread "AWT-EventQueue-0" java.lang.ArrayStoreException
        at java.lang.System.arraycopy(Native Method)
        at java.util.ArrayList.toArray(ArrayList.java:390)
        at de.fau.osr.gui.Viewer.ShowRequirements(Viewer.java:218)
        at de.fau.osr.gui.MouseEvent.mousePressed(MouseEvent.java:31)
        at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:280)
        at java.awt.Component.processMouseEvent(Component.java:6513)
        at javax.swing.JComponent.processMouseEvent(JComponent.java:3312)
        at java.awt.Component.processEvent(Component.java:6281)
        at java.awt.Container.processEvent(Container.java:2229)
        at java.awt.Component.dispatchEventImpl(Component.java:4872)
        at java.awt.Container.dispatchEventImpl(Container.java:2287)
        at java.awt.Component.dispatchEvent(Component.java:4698)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832)
        at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4489)
        at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422)
        at java.awt.Container.dispatchEventImpl(Container.java:2273)
        at java.awt.Window.dispatchEventImpl(Window.java:2719)
        at java.awt.Component.dispatchEvent(Component.java:4698)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:740)
        at java.awt.EventQueue.access$300(EventQueue.java:103)
        at java.awt.EventQueue$3.run(EventQueue.java:699)
        at java.awt.EventQueue$3.run(EventQueue.java:697)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
        at java.awt.EventQueue$4.run(EventQueue.java:713)
        at java.awt.EventQueue$4.run(EventQueue.java:711)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:710)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
```
occurs every time I click on a file in the "show all files" mode.
I guess since this is not fatal and we will replace that code we can just leave this unfixed, just wanted to say I observed it.

**Comment by uv48uson** [comment]
I think i fixed it. However the exception doesnt occur on my system anymore. With the newest push to Branch Req-17. Please comment if anybody can reproduce the exception or whether it is gone for u. Then we could close the issue.

**Comment by TPolzer** [comment]
Gone for me. Closing.
